version: "3"

services:

    laravel-app:
        build: .
        container_name: laravel-app
        # entrypoint: dockerize -wait tcp://laravel-db:3306 -timeout 40s ./.docker/entrypoint.sh
        # environment:
        #     - DB_HOST=laravel-db
        #     - DB_DATABASE=laravel
        #     - DB_USERNAME=root
        #     - DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - laravel-db
            - laravel-redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: ./.docker/nginx/entrypoint.sh
        environment:
            - NGINX_HOST=laravel-app
            - NGINX_PORT=9000
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - laravel-app

    laravel-db:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: laravel-db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    laravel-redis:
        image: redis:alpine
        container_name: laravel-redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
